# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST  http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="laysa.mp3"
Content-Type: audio/mpeg

< ./laysa.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/eca9a314-2ee6-4582-8478-03c2e733cd33/transcription
Content-Type: application/json

{
  "prompt": "François quesnay, médico"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "eca9a314-2ee6-4582-8478-03c2e733cd33",
  "temperature": 0.5,
  "prompt": "Gere um resumo suncinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}